cmake_minimum_required(VERSION 2.8...3.15)
project(eargs LANGUAGES C CXX)

add_library(${PROJECT_NAME} INTERFACE)
target_include_directories(${PROJECT_NAME} INTERFACE includes)
target_compile_features(${PROJECT_NAME} INTERFACE cxx_std_20)

get_directory_property(IS_SUBPROJECT PARENT_DIRECTORY)
if(IS_SUBPROJECT)
    set(EARGS_TESTS_DEFAULT OFF)
else()
    set(EARGS_TESTS_DEFAULT ON)
endif()
option(EARGS_BUILD_TESTS "Build eargs regression tests" ${EARGS_TESTS_DEFAULT})
if(EARGS_BUILD_TESTS)
    enable_testing()
    add_subdirectory(tests)
endif()
